/* Google Sheet deck: paste the sheet's "Publish to web" CSV link between the quotes.
   Columns: Name, Description, Category, Points (1-4). Leave it empty to use the cards below. */
const SHEET_CSV_URL = '';

/* Monikers card deck. Each card: [name, description, category, points 1-4]. Edit freely. */
const CAT = {PEOPLE:'PEOPLE', PLACES:'PLACES', PINOY:'PINOY', NET:'INTERNET', THINGS:'THINGS', ETC:'ET CETERA'};
const CARDS = [
 ["Cleopatra","Last active ruler of Ptolemaic Egypt. Allied with Julius Caesar and Mark Antony, and ended things with a snake, as the story goes.",CAT.PEOPLE,2],
 ["Leonardo da Vinci","Painted the Mona Lisa, sketched flying machines, and wrote his notes backwards in mirror script.",CAT.PEOPLE,1],
 ["Marie Curie","First person to win Nobel Prizes in two different sciences. Her notebooks are still too radioactive to handle bare-handed.",CAT.PEOPLE,2],
 ["Lapu-Lapu","Datu of Mactan whose warriors defeated Magellan's men in 1521. His statue stands on Mactan Island.",CAT.PINOY,2],
 ["José Rizal","National hero of the Philippines. Novelist, eye doctor, and the face on the one-peso coin.",CAT.PINOY,1],
 ["Sherlock Holmes","Detective at 221B Baker Street who looks at the mud on your shoes and tells you where you've been all week.",CAT.PEOPLE,1],
 ["Dracula","Count from Transylvania. Sleeps in a coffin, hates garlic, and never shows up in mirrors.",CAT.PEOPLE,1],
 ["The Tooth Fairy","Swaps coins for baby teeth left under pillows. The business model has never been explained.",CAT.ETC,1],
 ["Mall security guard","Pokes your bag with a stick for half a second and waves you in.",CAT.PINOY,2],
 ["Napoleon","French emperor famous for being short, which he wasn't. Lost it all at Waterloo.",CAT.PEOPLE,2],
 ["Frida Kahlo","Mexican painter known for bold self-portraits, a proud unibrow, and flowers in her hair.",CAT.PEOPLE,2],
 ["Your lola","Asks if you've eaten, then feeds you again anyway.",CAT.PINOY,1],
 ["Medusa","Greek monster with snakes for hair. One look at her face turns you to stone.",CAT.PEOPLE,1],
 ["Van Gogh's ear","The part of the painter that went missing in Arles in 1888.",CAT.ETC,3],
 ["The Wright brothers","Two bicycle makers from Ohio who flew the first powered airplane at Kitty Hawk in 1903.",CAT.PEOPLE,2],
 ["Sisyphus","Condemned to push a boulder up a hill forever, only to watch it roll back down every time.",CAT.PEOPLE,3],
 ["A substitute teacher","Puts on a movie, takes attendance wrong, and hopes for the best.",CAT.ETC,2],
 ["Chocolate Hills","More than a thousand grassy mounds in Bohol that turn brown in the dry season.",CAT.PINOY,1],
 ["The Bermuda Triangle","Stretch of the Atlantic blamed for ships and planes that vanished without a trace.",CAT.PLACES,2],
 ["Atlantis","Plato's legendary island city that sank into the sea in a single day and night.",CAT.PLACES,2],
 ["IKEA on a Saturday","A one-way maze of showrooms, meatballs, and couples arguing over a bookshelf.",CAT.PLACES,3],
 ["Mount Everest","Tallest mountain above sea level, now with actual traffic jams near the top.",CAT.PLACES,1],
 ["The Leaning Tower of Pisa","Italian bell tower that started tilting before it was even finished. Tourists pretend to hold it up.",CAT.PLACES,1],
 ["Area 51","Top-secret air base in the Nevada desert. Either testing planes or hiding aliens.",CAT.PLACES,2],
 ["Magellan's Cross","Cross planted in Cebu in 1521, now kept in a small chapel beside the Basilica del Santo Niño.",CAT.PINOY,3],
 ["The LTO line","Take a number, wait three hours, find out you're missing one photocopy.",CAT.PINOY,3],
 ["Stonehenge","Ring of giant standing stones in England. Nobody fully agrees on why it was built.",CAT.PLACES,2],
 ["The Titanic","The unsinkable ship that sank on its very first voyage in 1912.",CAT.THINGS,1],
 ["Jeepney","Loud, colorful public ride with a long bench on each side. Say \"para\" when you want to get off.",CAT.PINOY,1],
 ["Balut","Boiled duck egg with a surprise inside, sold at night with salt and vinegar.",CAT.PINOY,2],
 ["Videoke","Coin-operated karaoke machine that scores your singing out of 100, loudly and without mercy.",CAT.PINOY,1],
 ["Tabo","The plastic dipper found in every Filipino bathroom.",CAT.PINOY,2],
 ["Lechon","Whole roasted pig with crispy skin. The Cebu version needs no sauce.",CAT.PINOY,1],
 ["Double-dipping","Taking a bite and dipping back into the shared sauce. Everyone saw.",CAT.ETC,3],
 ["Pasalubong","The gift you're expected to bring back from every single trip.",CAT.PINOY,2],
 ["Brownout","Power goes out right when you need the electric fan the most.",CAT.PINOY,2],
 ["Ghosting","Ending a relationship by never replying again.",CAT.NET,1],
 ["Left on read","The message was seen. No reply is coming.",CAT.NET,2],
 ["Reply all","One company email, then five hundred replies asking to be taken off the list.",CAT.NET,3],
 ["A dad joke","A pun so bad it becomes good, delivered with full confidence.",CAT.ETC,1],
 ["The Macarena","1990s dance with hand moves in a fixed order and a hip wiggle at the end.",CAT.THINGS,2],
 ["A mosquito at 3 AM","One buzz near your ear and the night is over.",CAT.ETC,2],
 ["Stepping on a Lego","The sharpest pain known to parents, usually in the dark.",CAT.THINGS,1],
 ["The five-second rule","Dropped food is still fine to eat if you pick it up fast enough.",CAT.ETC,1],
 ["Buffering","Spinning circle that shows up at the best part of the movie.",CAT.NET,1],
 ["Captcha","Select every square with a traffic light to prove you're not a robot.",CAT.NET,2],
 ["Forgetting why you walked in","You came into the room for something. Now you're just standing there.",CAT.ETC,3],
 ["Participation trophy","Awarded for showing up.",CAT.THINGS,2],
 ["The floor is lava","Kids' game where you jump from sofa to chair to stay alive.",CAT.ETC,1],
 ["Rock, paper, scissors","Hand game for settling every important decision.",CAT.THINGS,1],
 ["Glass half full","The optimist's way of looking at the exact same amount of water.",CAT.ETC,3],
 ["Brain freeze","Sudden headache from eating something cold way too fast.",CAT.ETC,1],
 ["Hug or handshake","One person goes in for a hug, the other holds out a hand.",CAT.ETC,3],
 ["Chopping onions","Crying in the kitchen, but not because you're sad.",CAT.ETC,2],
 ["The last slice of pizza","Everyone wants it. Nobody takes it.",CAT.THINGS,2],
 ["Déjà vu","The strange feeling that you've lived this exact moment before.",CAT.ETC,3],
 ["Cat vs. glass of water","Eye contact, one paw, zero remorse.",CAT.NET,2],
 ["Hiccups","Little spasms you try to cure by holding your breath or getting scared.",CAT.ETC,1],
 ["Kilig","That giddy, butterflies-in-your-stomach feeling.",CAT.PINOY,3],
 ["Filipino time","Meeting at 3 means showing up at 4, maybe.",CAT.PINOY,2],
 ["Pointing with your lips","The Filipino way of giving directions without lifting a finger.",CAT.PINOY,3],
 ["The Big Bang","The moment everything started, around 13.8 billion years ago.",CAT.THINGS,2],
 ["A black hole","A spot in space where gravity is so strong that not even light gets out.",CAT.THINGS,2],
 ["Gravity","What Newton figured out when an apple fell, as the story goes.",CAT.THINGS,1],
 ["Photosynthesis","How plants turn sunlight, water, and air into food.",CAT.THINGS,2],
 ["Pinky promise","The most binding contract known to children.",CAT.ETC,1],
 ["A haunted doll","Sits in the corner and is never where you left it.",CAT.THINGS,2],
 ["Wi-Fi password on the fridge","Taped up for guests. Fourteen characters, half of them symbols.",CAT.NET,3],
 ["Running for the jeep","The sprint everyone knows when the ride starts pulling away.",CAT.PINOY,2],
 ["Holding in a sneeze","Face scrunched, eyes watering, it's coming anyway.",CAT.ETC,2],
 ["The Trojan Horse","Giant wooden gift that hid Greek soldiers inside.",CAT.THINGS,2],
 ["Laughing at your boss's joke","It wasn't funny. You laughed the loudest.",CAT.ETC,3],
 ["Tinikling","Folk dance where dancers hop between two clapping bamboo poles.",CAT.PINOY,2],
 ["Sinulog","Cebu's January festival for the Santo Niño, with drums and street dancing all day.",CAT.PINOY,2],
 ["Tsismis","Neighborhood gossip that somehow reaches everyone before lunch.",CAT.PINOY,2],
 ["A selfie stick","Lets you take a group photo with nobody left out, and everyone judging.",CAT.THINGS,1],
 ["Airplane mode","Turns your phone into a very expensive notebook.",CAT.NET,2],
 ["The Mona Lisa's smile","Is she smiling? It depends on where you look.",CAT.ETC,4],
 ["Autocorrect","Changes what you meant into something you'll have to explain later.",CAT.NET,2],
 ["Waiting for the rice cooker","The longest twenty minutes of any meal.",CAT.PINOY,4]
].map(([t,d,c,p],id)=>({id,t,d,c,p}));
